# Generated by Django 3.1.7 on 2021-03-31 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0004_customer_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='FIRSTAPPLICATION.place')),
                ('italian', models.BooleanField(default=False)),
                ('chinese', models.BooleanField(default=False)),
            ],
            bases=('FIRSTAPPLICATION.place',),
        ),
    ]
